Add drupal/tfa module to composer.json
docomoinnovations/cloud_orchestrator pull request #31
Opened 2023-09-14 07:50 UTC by sekinet813

2023-09-14 10:20 UTC, naoi requested changes
@sekinet813 Thank you for the PR.  I posted my comments.

2023-09-14 10:20 UTC, naoi commented on composer.json
> +    "drupal/real_aes": "^2.5",
@sekinet813 Can we change the version to `^2` for the dev branch?  We can put the specific version to the official release.

2023-09-14 10:20 UTC, naoi commented on composer.json
> +    "drupal/tfa": "^2.0",
@sekinet813 Can we change the version to `^2` for the dev branch?  We can put the specific version to the official release.

2023-09-15 01:06 UTC, KentaroHayashi-ipride commented
@sekinet813 @naoi 
It looks good to me.

2023-09-15 03:09 UTC, sekinet813 commented
@naoi @KentaroHayashi-ipride Thank you for your review. I modified it as you suggested, could you please check it?

2023-09-20 02:48 UTC, naoi approved these changes

2023-09-20 02:48 UTC, merged