#8 refactor composer.json
docomoinnovations/cloud_orchestrator pull request #9
Opened 2022-05-26 08:39 UTC by naoi

2022-05-26 15:35 UTC, baldwinlouie requested changes
Thanks for the patch.  I just have the one comment.

2022-05-26 15:35 UTC, baldwinlouie commented on composer.json
> +    "drupal/panels": "^4.6",
We can safely remove `drupal/page_manager` and `drupal/panels` now.  We are not using it anymore since we have our own dynamic homepage.

2022-05-26 18:31 UTC, naoi commented on composer.json
> +    "drupal/panels": "^4.6",
@baldwinlouie Thank you for your review.  I removed drupal/page_manager and drupal/panels.  Could you please double-check the patch?  Thanks

2022-05-27 15:21 UTC, baldwinlouie commented
@naoi Thank you for the updated patch.  It looks good to me now.

2022-05-27 17:13 UTC, naoi commented
@baldwinlouie Thank you for your review.  I'll merge the PR.  Thanks!

2022-05-27 17:14 UTC, merged